import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { I18nextProvider } from "./i18n/provider";
import { cookies } from "next/headers";
import { ToastProvider } from "@/components/common/ToastProvider";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"], 
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const preferredLang = cookieStore.get('preferredLanguage')?.value || 'en';
  return (
    <html lang="en" dir={preferredLang === 'ar' ? 'rtl' : 'ltr'}>
      <body
        className={`${poppins.variable} antialiased`}
        suppressHydrationWarning
      >
        <I18nextProvider initialLang={preferredLang}>
          <ToastProvider>
            {children}
          </ToastProvider>
        </I18nextProvider>
      </body>
    </html>
  );
}
